### ISSUE TITLE
Board Distortion

### ISSUE THREAD

**Issue by dobrienUNCG** [pawilliamson/CSC490-ChessEditor#31]
**Describe the bug**
I was messing around with some of the browser developer tools and managed to cause the board to display incorrectly.

**To Reproduce**
1. Run the application using 'ng serve --open'
2. Right click and select 'Inspect Element'
3. Open responsive design mode (Ctrl+Shift+M)
4. Decrease width below 240px

**Expected behavior**
The board's size should become static

**Screenshots**
~98px width
![image](https://user-images.githubusercontent.com/70172208/112360354-9bba3c00-8ca8-11eb-8441-1c38edda522a.png)
~170px width
![image](https://user-images.githubusercontent.com/70172208/112360596-dd4ae700-8ca8-11eb-9c89-f4ce46731459.png)

**Additional context**
This is a minor bug, but should be fixed. It is a CSS issue.

**Comment by MasterOfAllEvil** [comment]
Will be closed by Dakota's branch.
